# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01789e421b0eb24b7a373fdd0337cf4741b38064b9cf90b39c12e51aaee6b2764e7ef294b436f074252cb5165d1315ab295031d40039533fa0d4bda833b994e1

test:
  secret_key_base: 67fb2ce44b4c1b570ba42e42c005e0cd6dd13a564d4a804cf15589b1e425dd2003c88a7dea812ca19a40c81e0566ad92819924d1a46711bf8f95f45374fdc7e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
